apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-dashboard
  namespace: argocd
  labels:
    app: music-dashboard
    author: akash
spec:
  project: default
  
  # Source - Public GitHub Repository
  source:
    repoURL: https://github.com/madKrypton/argo-cd-demo
    targetRevision: HEAD
    path: k8s
  
  # Destination - Target Kubernetes cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: music-dashboard
  
  # Sync Policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences in certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
