apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: music-dashboard-project
  namespace: argocd
spec:
  description: Music Dashboard Application Project
  
  # Source repositories
  sourceRepos:
    - https://github.com/madKrypton/argo-cd-demo
  
  # Allowed destinations
  destinations:
    - namespace: music-app-dev
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  
  # Cluster resource whitelist
  # Only 'Namespace' is whitelisted to restrict cluster-wide changes and enhance security.
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  # Namespace resource whitelist
  # Only essential resources for application deployment and configuration are allowed:
  # Service, ConfigMap, Secret, Deployment, and Ingress.
  namespaceResourceWhitelist:
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: Ingress
