apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: music-app-qa

namePrefix: qa-

labels:
  - pairs:
      environment: qa
      managed-by: argocd

resources:
  - ../../base

replicas:
  - name: music-dashboard
    count: 3

images:
  - name: appukuttan/mastersong
    newTag: main-18

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
    target:
      kind: Deployment
      name: music-dashboard
